# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

# Automatically labels a pull request as "stacked PR" if it is stacked,
# i.e., not merging into the repo's default branch but into another PR.
#
# - Removes label automatically once target branch is changed to repo's default branch.
# - Prevents merging stacked PRs.
# - Ignores 'release/*' branches.

name: Label Stacked PRs

on:
  pull_request:
    types: [synchronize, opened, reopened, labeled, unlabeled, edited, closed]
    branches-ignore:
      - 'release/*'

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
  BASE_BRANCH: ${{ github.base_ref }}

jobs:
  remove-stacked-label:
    name: Remove Stacked Label
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/actions-ecosystem-remove-labels
      - name: remove label
        uses: actions-ecosystem/action-remove-labels@v1
        if: env.BASE_BRANCH == env.DEFAULT_BRANCH
        with:
          labels: stacked PR

  add-stacked-label:
    name: Add Stacked Label
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/actions-ecosystem-add-labels
      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        if: env.BASE_BRANCH != env.DEFAULT_BRANCH
        with:
          labels: stacked PR

  prevent-stacked-merge:
    needs: [add-stacked-label]
    name: Prevent Stacked Merge
    runs-on: ubuntu-latest
    steps:
      - name: prevent merge
        if: env.BASE_BRANCH != env.DEFAULT_BRANCH
        run: |
          echo "Pull request is stacked. Failing workflow to prevent merge."
          echo "Pull requests should only merge into the default branch: $DEFAULT_BRANCH"
          exit 1
